apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "pulsar-monitor.fullname" . }}-config"
data:
  runtime.yml: |-
    name: {{ .Values.config.name }}
    token: {{ .Values.config.pulsarClientToken }}
    trustStore: {{ .Values.config.trustStore }}
    analyticsConfig:
      apiKey: {{ .Values.config.analyticsApiKey }}
      ingestionURL: {{ .Values.config.analyticsUrl }}
      insightsWriteKey: {{ .Values.config.insightsWriteKey }}
      insightsAccountId: "{{ .Values.config.insightsAccountId }}"
    prometheusConfig:
      port: ":{{ .Values.service.port }}"
      exposeMetrics: {{ .Values.prometheus.enabled }}
      prometheusProxyURL: {{ .Values.prometheus.proxyURL }}
      prometheusProxyAPIKey: {{ .Values.prometheus.proxyAPIKey }}
    slackConfig:
      alertUrl: {{ .Values.config.alertUrl }}
    sitesConfig:
      sites:
        {{- toYaml .Values.sitesConfig | nindent 8 }}
    opsGenieConfig:
      intervalSeconds: 180
      heartbeatKey: {{ .Values.config.opsGenieHeartbeatKey }}
      heartbeatUrl: {{ .Values.config.opsGenieHeartbeatUrl }}
      alertKey: {{ .Values.config.opsGenieAlertKey }}
    pulsarAdminRestConfig:
      intervalSeconds: 120
      token: {{ .Values.config.pulsarClientToken }}
      clusters:
        {{- toYaml .Values.pulsarOpsClusters | nindent 8 }}
    pulsarTopicConfig:
        {{- toYaml .Values.topicConfigs | nindent 8 }}
    websocketConfig:
      {{- toYaml .Values.pulsarWebSocketConfigs | nindent 8 }}
